cc_library(
    name = "crosslist",
    hdrs = ["crosslist.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "crosslist_test",
    srcs = ["crosslist_test.cc"],
    deps = [
        ":crosslist",
        "@gtest//:gtest_main",
    ],
)
