cc_library(
    name = "listing",
    hdrs = ["listing.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "listing_test",
    srcs = ["listing_test.cc"],
    deps = [
        ":listing",
        "@gtest//:gtest_main",
    ],
)
