cc_library(
    name = "shape",
    hdrs = ["shape.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "shape_test",
    srcs = ["shape_test.cc"],
    deps = [
        ":shape",
        "@gtest//:gtest_main",
    ],
)
