cc_library(
    name = "ac",
    hdrs = ["ac.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "ac_test",
    srcs = ["ac_test.cc"],
    deps = [
        ":ac",
        "@gtest//:gtest_main",
    ],
)
