cc_library(
    name = "tree",
    hdrs = ["tree.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "tree_test",
    srcs = ["tree_test.cc"],
    deps = [
        ":tree",
        "@gtest//:gtest_main",
    ],
)
